version: '3.1'

services:
  perftest-front:
    container_name: perftest-front
    build:
      context: ./perftest-front
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
      
  perftest-back:
    container_name: perftest-back
    build:
      context: ./perftest-back
      dockerfile: ./docker/Dockerfile
    ports:
      - 3001:3001
    environment:
      - APIKEY=$APIKEY
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PW=example
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
